ajax_post/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls',namespace="myapp")),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

myapp/urls.py
from django.urls import path
from .views import (
    home_page,
    create_post_page,
    post_comment,
    search_posts,
    delete_post,
    edit_post,
    about,
    )
    
app_name = "myapp"

urlpatterns = [
  path("",home_page,name="home_page"),
  path("about",about,name="about"),
  path('create-post',create_post_page,name='create_post_page'),
  path("search",search_posts,name="search_posts"),
  path("<int:year>/<int:month>/<int:day>/<slug:post>",post_comment,name="post_comment"),
  path("<int:month>/<slug:post>/delete",delete_post,name="delete_post"),
  path("<int:day>/<slug:url>/edit",edit_post,name="edit_post"),
  
]

myapp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.
class Post(models.Model):
  title = models.CharField(max_length = 200)
  description = models.TextField(null = True, blank = True)
  image = models.FileField(null = True,blank=True)
  slug = models.SlugField(
    max_length=200,
    unique_for_date="publish",
    default="",
    )
  publish = models.DateTimeField(default=timezone.now)
  def get_absolute_url(self):
    return reverse("myapp:post_comment",
          args = [
              self.publish.year,
              self.publish.month,
              self.publish.day,
              self.slug,
            ]
        )
  def get_delete_post_url(self):
    return reverse("myapp:delete_post",
        args = [
            self.publish.month,
            self.slug,
          ]
    )
  def edit_post_url(self):
    return reverse("myapp:edit_post",
        args = [
            self.publish.day,
            self.slug,
            
          ]
      )
  class Meta:
    ordering = ("-publish",)
  def __str__(self):
    return self.title
    
class Comment(models.Model):
  post = models.ForeignKey(Post,
      on_delete = models.CASCADE,
      max_length = 200,
      related_name = "posts",
  )
  name = models.CharField(max_length=200)
  body = models.TextField()
  publish = models.DateTimeField(default=timezone.now)
  active = models.BooleanField(default=True)
  class Meta:
    ordering = ("-publish",)
  def __str__(self):
    return self.name

myapp/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.urls import reverse
import random
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
# Create your views csrf_exemf
from .models import Post,Comment

def slug_concat(title):
  s = title
  c = ""
  l = len(s.split(" "))
  for i in range(l):
    c += (s.split(" ")[i]+"-")
  rem = ""
  for i,v in enumerate(c):
    if i != len(c)-1:
      rem += v
    else:
      break
  return rem

def home_page(request):
  objects = Post.objects.all();
  paginator = Paginator(objects,3)
  page = request.GET.get("page")
  try:
    posts = paginator.page(page)
  except PageNotAnInteger:
    posts = paginator.page(1)
  except EmptyPage:
    posts = paginator.page(paginator.num_pages)
  context = {
    "posts":posts,
    'paginator':paginator,
  }
  return render(request, "home_page.html",context)
def search_posts(request):
  if(request.method == "GET"):
    search_query = request.GET.get("query")
    posts = []
    title_query = Post.objects.filter(title__contains=search_query)
    description_query = Post.objects.filter(description__contains=search_query)
    for q in title_query:
      if search_query != "":
        if q not in posts:
          posts.append(q)
    for q in description_query:
      if search_query != "":
        if q not in posts:
          posts.append(q)
  context = {
    "posts":posts,
    "query":search_query,
    "result":len(posts),
  }
  return render (request,"search_post.html",context)
def create_post_page(request):
  if(request.method == "POST"):
    title = request.POST.get('title')
    description = request.POST.get("description")
    image = request.FILES.get('image')
    post = Post(title=title,description=description,image=image)
    check = Post.objects.filter(title=title).exists()
    if check:
      ran = str(random.randint(0,1000))
      title = f"{title} {ran}"
    c = slug_concat(title)
    if Post.objects.filter(slug=c.lower()).exists():
      c = c.lower()+str(random.randint(0,1000))
    post.slug = c.lower()
    post.save()
  context = {
    
  }
  return render (request,"create_post.html",context)
def post_comment(request,year,month,day,post):
  posts = get_object_or_404(Post,
            publish__year = year,
            publish__month = month,
            publish__day = day,
            slug = post    
            )
  comments = posts.posts.filter(active=True)
  current_name = None
  if request.POST.get("action") == "post_comment":
    if request.method == "POST":
      name = request.POST.get("name")
      body = request.POST["body"]
      Comment.objects.create(
          post=posts,
          name = name,
          body = body,
        )
      return HttpResponseRedirect(reverse("myapp:post_comment",args=[posts.publish.year,posts.publish.month,posts.publish.day,posts.slug]))
  context = {
    "post":posts,
    "comments":comments,
    "current_name":current_name,
  }
  return render (request ,"post_comment.html",context)
def delete_post(request,month,post):
  posts = get_object_or_404(Post,
                      publish__month=month,
                      slug=post,
                  )
  if(request.method == "DELETE"):
    posts.delete()
    return HttpResponseRedirect(reverse("myapp:home_page"))
  context = {
    "post":posts
  }
  return render(request, "delete_post.html",context)
def edit_post(request,day,url):
  post = get_object_or_404(Post,publish__day=day,slug=url)
  if request.method == "POST":
    title = request.POST.get("title")
    description = request.POST.get("description")
    image = request.FILES.get("image")
    
    mpost = Post.objects.get(title=post.title,slug=post.slug)
    mpost.title = title
    mpost.description = description
    mpost.image = image
    if Post.objects.filter(slug=slug_concat(title).lower()).exists():
      ran = random.randint(0,1000)
      title = f"{slug_concat(title).lower()} {ran} edited"
    mpost.slug = slug_concat(title).lower()
   
    mpost.save()
    
  context = {
    "post":post,
  }
  return render(request,"edit_post.html",context)
def about(request):
  
  return render(request,"about.html")

myapp/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
  #about_top{
    height: 150px;
    width: 150px;
    position: relative;
    left: 50%;
    transform: translateX(-50%);
  }
  .des1,.des2,.des3,.des4,.des5{
      font-family: Times New Roman;
      margin-top: 5%;
      line-height: 30px;
      font-variant: small-caps;
  }
</style>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-12">
      <img id="about_top" src="{% static 'myapp/logo/codeworld_transparent_logo.png' %}">
    </div>
    <div class="col-12">
        <center>
            <h4 style="font-variant:small-caps;font-family:Times New Roman;">Welcome to CodeWorld</h4>
        </center>
    <div class="col-12">
        <div class="des1">
            <p>I'm Smart Cyber, and I'm thrilled to introduce you to CodeWorld, your destination for all things coding and technology.</p>
        </div>
    </div>
    </div>
    <div class="col-12">
        <p class="des1">At CodeWorld, we're dedicated to providing you with a platform where you can unleash your creativity and technical skills. Whether you're a seasoned developer or just starting your coding journey, our platform is designed with you in mind.</p>
    </div>
    <div class="col-12">
        <li>Our Key Features:</li>
    </div>
    <div class="col-12">
        <p class="des2"><strong>Create Post</strong>: Dive into the world of coding by creating and sharing your projects and articles. Whether it's web development, app design, or tech tutorials, CodeWorld is your canvas for sharing your expertise.</p>
    </div>
    <div class="col-12">
        <p class="des3"> <strong> Edit Post:</strong> Modify your posts and projects whenever you need to make updates or improvements. We empower you to continuously refine your work and keep it up to date.</p>
    </div>
    <div class="col-12">
        <p class="des4"> <strong> Delete Post:</strong> Don't be afraid to experiment and make mistakes. If you want to remove a post or project, you can easily delete it.</p>
    </div>
    <div class="col-12">
        <p class="des5">Join us at CodeWorld and be a part of a thriving community of tech enthusiasts. Let's code, learn, and grow together!</p>
    </div>
  </div>
</div>
{% endblock %}

myapp/templates/base.html
<!DOCRYPE html>
{% load static %}
<html>
  <head>
    
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
      <link rel="stylesheet"href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <meta charset="utf-8">
    <meta name="viewport"content="width=device-width,initial-scale=1.0">
    <style>
      :root{
        --main-color:#4e6ef6;
      }
      #more_actions{
        align-items: center;
        display: flex;
       
       
      }
      a{
        text-decoration: none;
      }
      body{
        display: flex;
        flex-direction: column;
      }
      #more_btn{
        margin-bottom: 5%;
        display: none;
      }
      .show{
        transform: scale(1);
        
      }
      #more_actions li{
        list-style-type: none;
        background: #4e6ef6;
        color: #fff;
        border-radius: 10px;
        display: grid;
        place-items: center;
        height: 40px;
        width: 60px;
        margin-left: 2%;
        border: #4e6ef6 solid 1px;
        
        box-shadow: 0px 0px 15px rgba(0,0,0,0.20);
      }
      #more_actions a{
        text-decoration: none;
        color: #fff;
      }
      #more_actions ul{
        display: grid;
        place-content: center;
        grid-gap: 10px;
        grid-template-columns: repeat(2 ,1fr);
        justify-content: space-around;
        align-items: center;
        height: 30px;
       
      }
      body{
        display: flex;
        flex-direction: column;
        margin: 0;
        padding: 0;
      }
      main{
        flex:1 auto;
      }
      footer{
        height: 180px;
        width: 95%;
        background: #fff;
        
      }
      .material-icons{
        background-color: transparent;
        border:none;
        outline: none;
        color: #fff;
        display: block;
      }
      #search-bar{
        margin-top: 5%;
      }
      #search-ic{
        height: 100%;
        width: 25px;
        position: absolute;
        left: 85%;
        top:50%;
        background-color:transparent;
        border: none;
        outline: none;
        padding-left: 5px;
        background-size: contain;
        background-position: center;
        background-repeat: no-repeat;
        background-image: url('/static/admin/img/search.svg');
        background: ;
        transform: translateY(-50%);
      }
      #logo{
        height: 30px;
        width: 30px;
        background: #fff;
        border-radius: 50%;
        
      }
      h5 a{
        color: #000000;
        font-size: small;
        font-variant: small-caps;
      }
      #top_logo{
        height: 40px;
        width: 40px;
      }
    </style>
  </head>
  <header>
  </header>
    <nav class="navbar navbar-dark" style="background:var(--main-color);">
   <div class="navbar-header p-2">
     <img id="top_logo" src="{% static '/myapp/logo/codeworld_transparent_logo.png' %}">
     <a style="font-variant:small-caps;font-size:x-large;" class="navbar-brand " href="{% url 'myapp:home_page' %}"><span>CodeWorld</span></a>
   </div>
   <button id="menu" class="material-icons">menu</button>
    <div id="collapse" class="collapse p-2">
      <ul class="navbar-nav p-2">
        <li class="nav-item">
          <a style="font-variant:small-caps;" class="nav-link active " href="{% url 'myapp:create_post_page' %}">Create Post</a>
          <a style="font-variant:small-caps;" class="nav-link active " href="{% url 'myapp:about' %}">About</a>
          <a style="font-variant:small-ca>ps;" class="nav-link active " href="#logo">Contact Us</a>
        </li>
      </ul>
    </div>
  </nav>
  <body>
    {% block content %}
    
    {% endblock %}
    <script type="text/javascript">
      $(document).ready(function(){
        $("#menu").click(function(){
          if($(this).text()  == "menu"){
            $(this).text("close")
            $("#collapse").attr('class','navbar-collapse')
          }
          else{
            
            $(this).text("menu")
            $("#collapse").attr('class','collapse')
            
          }
        })
      })
     
    </script>
    {% block footer %}
    <main></main>
    <footer>
      <div class="container p-3 m-3">
        <h5>Contact us</h5>
        <div style="margin-top:5%;" class="row justify-content-md-center">
          <div class="col">
            <a href="#">
              <img id="logo" src="{% static 'myapp/logo/facebook_logo.png' %}">
            </a>
          </div>
          
          <div class="col">
            <h5><a href="#">Facebook</a></h5>
          </div>
        </div>
        <div style="margin-top:5%;" class="row">
          <div class="col">
            <a href="https://wa.me/+2348085083832">
              <img id="logo" src="{% static 'myapp/logo/whatsapp_logo.png' %}">
            </a>
          </div>
         
          <div class="col">
            <h5><a href="https://wa.me/+2348085083832">WhatsApp</a></h5>
          </div>
        </div>
        <div style="margin-top:5%;" class="row">
          <div class="col">
            <a href="#">
              <img id="logo" src="{% static 'myapp/logo/telegram_logo.png' %}">
            </a>
          </div>
          
          <div class="col">
            <h5><a href="#">Telegram</a>
          </div>
        </div>
      </div>
    </footer>
    <span style="color:#000;margin-top:5%;">&copy;copyright 2023</span>
    {% endblock %}
  </body>
</html>

myapp/templates/create_post.html
{% extends 'base.html' %}

{% block content %}
<form action="" class="p-4">
  {% csrf_token %}
  <div class="form-group">
    <label class="form-label" for="title">Title:</label>
    <input id="title" type="text" class="form-control" placeholder="type post title...">
  </div>
  <div class="form-group">
    <label for="description" class="form-label">Description:</label>
    <textarea id="description" class="form-control" placeholder="type post description..."></textarea>
  </div>
  <div class="form-group">
    <label for="file" class="form-label">Upload image:</label>
    <input id="image" type="file" class="form-control">
  </div>
  <button id="submit" class="btn btn-primary m-3" type="button" style="width:100px; transform: translateX(80%);">Post</button>
</form>
<script type="text/javascript">
  
  $(document).ready(function(){
    let formData = new FormData()
    $("#submit").click(function(){
      if($("#title").val().length == 0){
        $("#title").attr("class","form-control alert-danger")
      }
      else{
        $("#title").attr("class","form-control")
        if($("#image").val().length < 4){
          $("#image").attr("class","form-control alert-danger")
        }
        else{
          $("#image").attr("class","")
          formData.append("title",$("#title").val())
          formData.append('description',$('#description').val())
          formData.append('image',$("#image")[0].files[0])
          formData.append('action','create_post_page')
          formData.append('csrfmiddlewaretoken', '{{csrf_token}}')
             $.ajax({
                  type:'POST',
                  url:'{% url "myapp:create_post_page" %}',
                  data:formData,
                  cache:false,
                  processData:false,
                  contentType:false,
                  enctype:'multipart/form-data',
                  success: function (res){
                      alert(res.status +" New Post has been Created Successfully!")
                      $("#title").val("")
                      $("#description").val("")
                      $("#image").val("")
                  },
                  error: function (xhr, errmsg, err){
                      const errorResponseMessage = xhr.status + ":" + xhr.responseText
                      console.log(errorResponseMessage);
                      alert(errorResponseMessage);
                  }
            })
        }
      }
    })
  })
</script>
{% endblock %}

myapp/templates/delete_post.html
{% extends 'base.html' %} 
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% block content %}
<div style="margin-top:5%;" class="container">
  <center>
    <h5 style="font-variant:small-caps;">Delete Post</h5>
  </center>
  <div class="row">
    <div class="col">
      <div style="height:100%;" class="card p-3">
        <div class="view overlay">
          <img style="height:;" class="card-img-top" src="{{ post.image.url }}">
          <h3 class="card-title">{{ post.title }}</h3>
          <p class="card-text">{{ post.description }}</p>
        </div>
      </div>
    </div>
    
    <div class="col">
      <h4>Are you sure do You want to delete this post</h4>
      <button id="delete" class="btn btn-danger">DELETE</button>
      <button id="no" class="btn btn-success">Cancel</button>
    </div>
  </div>
</div>
 
<script type="text/javascript">
  $("#no").click(function(){
     window.open("{% url 'myapp:home_page' %}")
  })
  $(document).on("click","#delete",function(e){
        $.ajax({
          type:"DELETE",
          headers:{
            "X-CSRFToken":"{{ csrf_token }}",
          },
          success: function(){
            window.open("{% url 'myapp:home_page' %}")
          },
          error: function(){
            alert("something wrong")
          }
          
        })
    })
 
</script>
{% endblock %}

myapp/templates/edit_post.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top:5%;" class="container">
  <center>
    <h5 style="font-variant:small-caps;">Edit Post</h5>
  </center>
  <div style="margin-top:5%;" class="row">
    <div class="col">
      <div class="card">
        <img  class="card-img-top" src="{{ post.image.url }}">
        <input id="file" type="file" class="form-control">
      </div>
      
    </div>
    <div class="col">
       <input id="title" style="font-size:x-large;" type="text" class="form-control card-title" value="{{ post.title }}" >
        <textarea id="description" rows="5" class="form-control card-text">{{ post.description }}</textarea>
        <button id="submit" style="margin-top:5%;margin-bottom:5%;" class="btn btn-success">Save changes</button>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(function(){
    $("#submit").click(function(){
      if($("#file").val().length <= 4){
        $("#file").attr("class","alert alert-danger form-control")
      }else{
        $("#file").attr("class","form-control")
        if($("#title").val().length == 0){
          $("#title").attr("class","alert alert-danger form-control")
        }else{
          var form = new FormData()
          form.append("title",$("#title").val())
          form.append("description",$("#description").val())
          form.append("image",$("#file")[0].files[0])
          form.append("action","edit_post")
          form.append("csrfmiddlewaretoken","{{ csrf_token }}")
          $("#title").attr("class","form-control")
          $.ajax({
            type:"POST",
            url:"{% url 'myapp:edit_post' post.publish.day post.slug %}",
            data:form,
            processData:false,
            cache:false,
            contentType:false,
            enctype:"multipart/form-data",
            success: function(){
              alert("edit complete")
              //window.open("{% url 'myapp:edit_post' post.publish.day post.slug %}")
            },
            error: function(){
              alert("something wrong")
            }
          })
        }
      }
      
    })
  })
</script>
{% endblock %}

myapp/templates/home_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-sm-12">
      <div style="background:var(--main-color);" class="card p-2 m-2">
        <form action="search" method="get">
          <input name="query" id="search-bar" placeholder="search post..." class="form-control">
          <button id="search-ic" type="submit"></button>
        </form>
      </div>
    </div>
    
    <div class="w-100"></div>
    {% for post in posts %}
      <div class="col m-2">
        <div class="card p-3">
          <div class="view overlay">
            <div id="more_actions">
              
              <ul id="more_items">
                <li><a href="{{ post.edit_post_url }}">Edit</a></li>
                <li><a href="{{ post.get_delete_post_url }}">Delete</a></li>
                
              </ul>
            </div>
            <img style="height:250px;width:100%;transform:translateX(0%);" src="{{ post.image.url }}" class="card-img-top" >
            <h3 class="card-title">{{ post.title }}</h3>
            <p class="card-text">{{ post.description }}</p>
            <div style="padding-left:20%;" class="btn-group">
              <div class="row justify-content-md-center">
                <div class="col">
                  <a style="color:#000;" href="{{ post.get_absolute_url }}" style="color:#0000;" class="material-icons">comment</a>
                </div>
                <div class="col">
                  <h5 style="color:#000;">{{ post.posts.count }}</h5>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    
    {% include 'pagination.html' with page=posts paginator=paginator %}
  </div>
  {% if posts.count > 2 %}
    
  {% endif %}
</div>
<script type="text/javascript">
  var more_items = document.querySelector("#more_items")
  
  window.onload = function(){
    hide()
  }
  function hide(){
    //more_items.style.transform = "scale(0)"
    //more_items.style.transitionDuration = "1s"
  }
  function show(btn){
   
    more_items.classList.toggle("show")
    if($(btn).text() == "more_vert"){
      $(btn).text("close")
    }
    else{
      $(btn).text("more_vert")
      more_items.classList.toggle("show")
    }
  }
  
  $(function(){
    
    $("#search-ic").click(function(){
      let query = $('#search-bar').val();
      $.ajax({
        type:"GET",
        data:{
          "query":query,
        },
        success: function(){
          
        },
        error:function(){
         
        }
      })
    })
  })
</script>
{% endblock %}

myapp/templates/pagination.html
{% load myapp_tags %}
<style>
  #next , #previous{
    color: #000000;
    font-size: xx-large;
    text-decoration: none;
  }
  #num_page{
    text-decoration: none;
    text-align: ;
    color: #000000;
  }
  #num_page_cont{
    background: #b9c6fe;
    display: grid;
    place-items: center;
    border: #fff solid 1px;
  }
  #pages{
    background: #d2dafb;
  }
</style>

{% if page.has_next or page.has_previous %}
<h5 style="font-variant:small-caps;">More Posts</h5>
<div id="pages" class="container">
  <div class="row justify-content-md-center">
    <div class="col">
      {% if page.has_previous %}
        <a id="previous" class="material-icons" href="?page={{ page.previous_page_number }}">arrow_left</a>
      {% endif %}
    </div>
    {% available_page paginator as all_pages  %}
      {% for num_page in all_pages %}
        <div id="num_page_cont" class="col">
          <a id="num_page" href="?page={{ num_page }}">{{ num_page }}</a>
        </div>
      {% endfor %}
    <div class="col">
      {% if page.has_next %}
        <a id="next" class="material-icons" href="?page={{ page.next_page_number }}">arrow_right</a>
      {% endif %}
    </div>
  </div>
</div>
{% endif %}
<script type="text/javascript">
  var current = window.location.href
  var urls = document.querySelectorAll('a')
  var all_pages = Array.from(urls)
  var num = {{ all_pages }}
  $(function(){
    all_pages.forEach((a)=>{
      
    })
  })
</script>

myapp/templates/post_comment.html
{% extends 'base.html' %} 
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% block content %}
<div class="container">
  <center>
    <h4>{{ comments.count }} Comments</h4>
  </center>
  <div class="row justify-content-md-center">
    <div class="col">
      <div class="card p-3">
        <div class="view overlay">
          <img style="height:;" class="card-img-top" src="{{ post.image.url }}">
          <h3 class="card-title">{{ post.title }}</h3>
          <p class="card-text">{{ post.description }}</p>
        </div>
      </div>
    </div>
    </div>
    <div class="row">
    <div class="col" >
      {% if comments.count != 0 %}
        <h4>Posted comments</h4>
      {% endif %}
      {% for comment in comments %}
      <div id="card" class="card p-2" style="border:#12649e solid 2px;margin-top:5%;">
        <div class="view overly">
          <h4 id="name" class="card-title">{{ comment.name }}</h4>
          <p id="body" class="card-text">{{ comment.body }}</p>
          <button  onclick="remove_comment(this);" id="remove_comment" style="color:red;font-size:xx-large;background:transparent;border:none;float:right;top:25%;position:absolute;left:90%;outline:none;"></button>
        </div>
      </div>
      {% empty %}
        <h4 style="font-variant:small-caps;">there is no comments yet!</h4>
      {% endfor %}
    </div>
    <div class="w-100"></div>
    <div class="col">
      <form action="" class="p-2">
        <p>post your comment here</p>
            <p id="a-e"></p>
        <div class="form-group">
          <label for="title" class="form-label">
            <input id="name" placeholder="type your name" type="text" class="form-control">
          </label>
        </div>
        <div class="form-group">
          <label for="body"body>
            <textarea id="body" cols="24.5" placeholder="type you comment here.." class="form-control"></textarea>
          </label>
          <div class="form-group">
            <button id="submit" type="button" class="btn btn-primary" style="transform:translateX(50%);margin-top:4%;">Post comment</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
 
<script type="text/javascript">
  var a_e = document.getElementById("a-e")
  var card = document.getElementById("card")
  function remove_comment(btn){
    
  }
  $(document).on("click","#submit",function(e){
    e.preventDefault();
    let name = $("#name").val();
    let body = $("#body").val();
    if(name.length == 0 || body.length == 0){
        a_e.setAttribute("class","alert alert-warning")
        a_e.innerText = "All Fields are require"
    }
    else{
        a_e.setAttribute("class","")
        a_e.innerText = ""
        $.ajax({
          type:"POST",
          data:{
            "name":name,
            "body":body,
            "action":"post_comment",
            "csrfmiddlewaretoken":"{{csrf_token}}",
          },
          success: function(){
           
            name = ""
            body = ""
            window.open("{% url 'myapp:post_comment' post.publish.year post.publish.month post.publish.day post.slug %}")
            
          },
          error: function(){
            alert("something wrong")
          }
          
        })
    } 
  })
</script>
{% endblock %}

myapp/templates/search_post.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <div class="card m-2 p-2">
        <h6 class="text-center">Search for <span style="font-size:large;">"{{ query }}"</span></h6>
        <p class="text-center">{{ result }} Result</p>
      </div>
    </div>
    <div class="w-100"></div>
    {% for post in posts %}
      <div class="col md-2">
        <div class="card p-3">
           
            <div id="more_actions">
              
              <ul id="more_items">
                <li><a href="{{ post.edit_post_url }}">Edit</a></li>
                <li><a href="{{ post.get_delete_post_url }}">Delete</a></li>
                
              </ul>
            </div>
          <div class="view overlay">
            <img style="height:250px;width:100%;transform:translateX(0%);" src="{{ post.image.url }}" class="card-img-top" >
            <h3 class="card-title">{{ post.title }}</h3>
            <p class="card-text">{{ post.description }}</p>
            <div style="padding-left:20%;" class="btn-group">
              <div class="row justify-content-md-center">
                <div class="col">
                  <a style="color:#000;" href="{{ post.get_absolute_url }}" style="color:#0000;" class="material-icons">comment</a>
                </div>
                <div class="col">
                  <h5 style="color:#000;">{{ post.posts.count }}</h5>
                </div>
              </div>
              <a href="#" ><button class="btn btn-default"></button></a>
              
            </div>
          </div>
       
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}